//
// (C) Copyright SimpliRoute.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.14.0
// source: simpli-echo-me/simpliEchoMe.proto

package simpli_echo_me

import (
	proto "github.com/golang/protobuf/proto"
	_ "gitlab.com/simpliroute/proto-gen-go/simpli-echo-me/src/commons/global"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// A greeting.
type SayHiResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// A greeting message.
	Greeting string `protobuf:"bytes,1,opt,name=greeting,proto3" json:"greeting,omitempty"`
}

func (x *SayHiResponse) Reset() {
	*x = SayHiResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_simpli_echo_me_simpliEchoMe_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SayHiResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SayHiResponse) ProtoMessage() {}

func (x *SayHiResponse) ProtoReflect() protoreflect.Message {
	mi := &file_simpli_echo_me_simpliEchoMe_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SayHiResponse.ProtoReflect.Descriptor instead.
func (*SayHiResponse) Descriptor() ([]byte, []int) {
	return file_simpli_echo_me_simpliEchoMe_proto_rawDescGZIP(), []int{0}
}

func (x *SayHiResponse) GetGreeting() string {
	if x != nil {
		return x.Greeting
	}
	return ""
}

// An Echo service request.
type EchoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// A name to include in the greeting.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *EchoRequest) Reset() {
	*x = EchoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_simpli_echo_me_simpliEchoMe_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EchoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoRequest) ProtoMessage() {}

func (x *EchoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_simpli_echo_me_simpliEchoMe_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoRequest.ProtoReflect.Descriptor instead.
func (*EchoRequest) Descriptor() ([]byte, []int) {
	return file_simpli_echo_me_simpliEchoMe_proto_rawDescGZIP(), []int{1}
}

func (x *EchoRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// An Echo service response.
type EchoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// A greeting message with a name.
	Greeting string `protobuf:"bytes,1,opt,name=greeting,proto3" json:"greeting,omitempty"`
}

func (x *EchoResponse) Reset() {
	*x = EchoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_simpli_echo_me_simpliEchoMe_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EchoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoResponse) ProtoMessage() {}

func (x *EchoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_simpli_echo_me_simpliEchoMe_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoResponse.ProtoReflect.Descriptor instead.
func (*EchoResponse) Descriptor() ([]byte, []int) {
	return file_simpli_echo_me_simpliEchoMe_proto_rawDescGZIP(), []int{2}
}

func (x *EchoResponse) GetGreeting() string {
	if x != nil {
		return x.Greeting
	}
	return ""
}

// An EchoRemember service request.
type EchoRememberRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// A name to remember.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *EchoRememberRequest) Reset() {
	*x = EchoRememberRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_simpli_echo_me_simpliEchoMe_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EchoRememberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoRememberRequest) ProtoMessage() {}

func (x *EchoRememberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_simpli_echo_me_simpliEchoMe_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoRememberRequest.ProtoReflect.Descriptor instead.
func (*EchoRememberRequest) Descriptor() ([]byte, []int) {
	return file_simpli_echo_me_simpliEchoMe_proto_rawDescGZIP(), []int{3}
}

func (x *EchoRememberRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// An EchoRemember service response.
type EchoRememberResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// A unique identifier.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *EchoRememberResponse) Reset() {
	*x = EchoRememberResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_simpli_echo_me_simpliEchoMe_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EchoRememberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoRememberResponse) ProtoMessage() {}

func (x *EchoRememberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_simpli_echo_me_simpliEchoMe_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoRememberResponse.ProtoReflect.Descriptor instead.
func (*EchoRememberResponse) Descriptor() ([]byte, []int) {
	return file_simpli_echo_me_simpliEchoMe_proto_rawDescGZIP(), []int{4}
}

func (x *EchoRememberResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// A SayHiRemember service request.
type SayHiRememberRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// A identifier of the name to greet.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *SayHiRememberRequest) Reset() {
	*x = SayHiRememberRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_simpli_echo_me_simpliEchoMe_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SayHiRememberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SayHiRememberRequest) ProtoMessage() {}

func (x *SayHiRememberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_simpli_echo_me_simpliEchoMe_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SayHiRememberRequest.ProtoReflect.Descriptor instead.
func (*SayHiRememberRequest) Descriptor() ([]byte, []int) {
	return file_simpli_echo_me_simpliEchoMe_proto_rawDescGZIP(), []int{5}
}

func (x *SayHiRememberRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// A SayHiRemember service response.
type SayHiRememberResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// A greeting message with a name.
	Greeting string `protobuf:"bytes,1,opt,name=greeting,proto3" json:"greeting,omitempty"`
}

func (x *SayHiRememberResponse) Reset() {
	*x = SayHiRememberResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_simpli_echo_me_simpliEchoMe_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SayHiRememberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SayHiRememberResponse) ProtoMessage() {}

func (x *SayHiRememberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_simpli_echo_me_simpliEchoMe_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SayHiRememberResponse.ProtoReflect.Descriptor instead.
func (*SayHiRememberResponse) Descriptor() ([]byte, []int) {
	return file_simpli_echo_me_simpliEchoMe_proto_rawDescGZIP(), []int{6}
}

func (x *SayHiRememberResponse) GetGreeting() string {
	if x != nil {
		return x.Greeting
	}
	return ""
}

var File_simpli_echo_me_simpliEchoMe_proto protoreflect.FileDescriptor

var file_simpli_echo_me_simpliEchoMe_proto_rawDesc = []byte{
	0x0a, 0x21, 0x73, 0x69, 0x6d, 0x70, 0x6c, 0x69, 0x2d, 0x65, 0x63, 0x68, 0x6f, 0x2d, 0x6d, 0x65,
	0x2f, 0x73, 0x69, 0x6d, 0x70, 0x6c, 0x69, 0x45, 0x63, 0x68, 0x6f, 0x4d, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x15, 0x73, 0x69, 0x6d, 0x70, 0x6c, 0x69, 0x2e, 0x73, 0x69, 0x6d, 0x70,
	0x6c, 0x69, 0x5f, 0x65, 0x63, 0x68, 0x6f, 0x5f, 0x6d, 0x65, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x73, 0x2f, 0x67,
	0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x2f, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2b, 0x0a, 0x0d, 0x53, 0x61, 0x79, 0x48, 0x69, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x67, 0x72, 0x65, 0x65, 0x74,
	0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x67, 0x72, 0x65, 0x65, 0x74,
	0x69, 0x6e, 0x67, 0x22, 0x21, 0x0a, 0x0b, 0x45, 0x63, 0x68, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x2a, 0x0a, 0x0c, 0x45, 0x63, 0x68, 0x6f, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x67, 0x72, 0x65, 0x65, 0x74, 0x69,
	0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x67, 0x72, 0x65, 0x65, 0x74, 0x69,
	0x6e, 0x67, 0x22, 0x3d, 0x0a, 0x13, 0x45, 0x63, 0x68, 0x6f, 0x52, 0x65, 0x6d, 0x65, 0x6d, 0x62,
	0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x3a, 0x12, 0xc2,
	0xf3, 0x18, 0x0e, 0x73, 0x69, 0x6d, 0x70, 0x6c, 0x69, 0x5f, 0x65, 0x63, 0x68, 0x6f, 0x5f, 0x6d,
	0x65, 0x22, 0x26, 0x0a, 0x14, 0x45, 0x63, 0x68, 0x6f, 0x52, 0x65, 0x6d, 0x65, 0x6d, 0x62, 0x65,
	0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x26, 0x0a, 0x14, 0x53, 0x61, 0x79,
	0x48, 0x69, 0x52, 0x65, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x22, 0x33, 0x0a, 0x15, 0x53, 0x61, 0x79, 0x48, 0x69, 0x52, 0x65, 0x6d, 0x65, 0x6d, 0x62,
	0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x67, 0x72,
	0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x67, 0x72,
	0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x32, 0xdd, 0x03, 0x0a, 0x13, 0x53, 0x69, 0x6d, 0x70, 0x6c,
	0x69, 0x45, 0x63, 0x68, 0x6f, 0x4d, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x55,
	0x0a, 0x05, 0x53, 0x61, 0x79, 0x48, 0x69, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a,
	0x24, 0x2e, 0x73, 0x69, 0x6d, 0x70, 0x6c, 0x69, 0x2e, 0x73, 0x69, 0x6d, 0x70, 0x6c, 0x69, 0x5f,
	0x65, 0x63, 0x68, 0x6f, 0x5f, 0x6d, 0x65, 0x2e, 0x53, 0x61, 0x79, 0x48, 0x69, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x0e, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x08, 0x12, 0x06, 0x2f,
	0x53, 0x61, 0x79, 0x48, 0x69, 0x12, 0x65, 0x0a, 0x04, 0x45, 0x63, 0x68, 0x6f, 0x12, 0x22, 0x2e,
	0x73, 0x69, 0x6d, 0x70, 0x6c, 0x69, 0x2e, 0x73, 0x69, 0x6d, 0x70, 0x6c, 0x69, 0x5f, 0x65, 0x63,
	0x68, 0x6f, 0x5f, 0x6d, 0x65, 0x2e, 0x45, 0x63, 0x68, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x23, 0x2e, 0x73, 0x69, 0x6d, 0x70, 0x6c, 0x69, 0x2e, 0x73, 0x69, 0x6d, 0x70, 0x6c,
	0x69, 0x5f, 0x65, 0x63, 0x68, 0x6f, 0x5f, 0x6d, 0x65, 0x2e, 0x45, 0x63, 0x68, 0x6f, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x14, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0e, 0x12, 0x0c,
	0x2f, 0x45, 0x63, 0x68, 0x6f, 0x2f, 0x7b, 0x6e, 0x61, 0x6d, 0x65, 0x7d, 0x12, 0x7e, 0x0a, 0x0c,
	0x45, 0x63, 0x68, 0x6f, 0x52, 0x65, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x2a, 0x2e, 0x73,
	0x69, 0x6d, 0x70, 0x6c, 0x69, 0x2e, 0x73, 0x69, 0x6d, 0x70, 0x6c, 0x69, 0x5f, 0x65, 0x63, 0x68,
	0x6f, 0x5f, 0x6d, 0x65, 0x2e, 0x45, 0x63, 0x68, 0x6f, 0x52, 0x65, 0x6d, 0x65, 0x6d, 0x62, 0x65,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2b, 0x2e, 0x73, 0x69, 0x6d, 0x70, 0x6c,
	0x69, 0x2e, 0x73, 0x69, 0x6d, 0x70, 0x6c, 0x69, 0x5f, 0x65, 0x63, 0x68, 0x6f, 0x5f, 0x6d, 0x65,
	0x2e, 0x45, 0x63, 0x68, 0x6f, 0x52, 0x65, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x15, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0f, 0x1a, 0x0d, 0x2f,
	0x45, 0x63, 0x68, 0x6f, 0x52, 0x65, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x87, 0x01, 0x0a,
	0x0d, 0x53, 0x61, 0x79, 0x48, 0x69, 0x52, 0x65, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x2b,
	0x2e, 0x73, 0x69, 0x6d, 0x70, 0x6c, 0x69, 0x2e, 0x73, 0x69, 0x6d, 0x70, 0x6c, 0x69, 0x5f, 0x65,
	0x63, 0x68, 0x6f, 0x5f, 0x6d, 0x65, 0x2e, 0x53, 0x61, 0x79, 0x48, 0x69, 0x52, 0x65, 0x6d, 0x65,
	0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2c, 0x2e, 0x73, 0x69,
	0x6d, 0x70, 0x6c, 0x69, 0x2e, 0x73, 0x69, 0x6d, 0x70, 0x6c, 0x69, 0x5f, 0x65, 0x63, 0x68, 0x6f,
	0x5f, 0x6d, 0x65, 0x2e, 0x53, 0x61, 0x79, 0x48, 0x69, 0x52, 0x65, 0x6d, 0x65, 0x6d, 0x62, 0x65,
	0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1b, 0x82, 0xd3, 0xe4, 0x93, 0x02,
	0x15, 0x12, 0x13, 0x2f, 0x53, 0x61, 0x79, 0x48, 0x69, 0x52, 0x65, 0x6d, 0x65, 0x6d, 0x62, 0x65,
	0x72, 0x2f, 0x7b, 0x69, 0x64, 0x7d, 0x42, 0x45, 0x0a, 0x19, 0x63, 0x6f, 0x6d, 0x2e, 0x73, 0x69,
	0x6d, 0x70, 0x6c, 0x69, 0x2e, 0x73, 0x69, 0x6d, 0x70, 0x6c, 0x69, 0x5f, 0x65, 0x63, 0x68, 0x6f,
	0x5f, 0x6d, 0x65, 0x50, 0x01, 0x5a, 0x26, 0x67, 0x69, 0x74, 0x6c, 0x61, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2d, 0x67, 0x65, 0x6e, 0x2d, 0x67, 0x6f, 0x2f, 0x73,
	0x69, 0x6d, 0x70, 0x6c, 0x69, 0x5f, 0x65, 0x63, 0x68, 0x6f, 0x5f, 0x6d, 0x65, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_simpli_echo_me_simpliEchoMe_proto_rawDescOnce sync.Once
	file_simpli_echo_me_simpliEchoMe_proto_rawDescData = file_simpli_echo_me_simpliEchoMe_proto_rawDesc
)

func file_simpli_echo_me_simpliEchoMe_proto_rawDescGZIP() []byte {
	file_simpli_echo_me_simpliEchoMe_proto_rawDescOnce.Do(func() {
		file_simpli_echo_me_simpliEchoMe_proto_rawDescData = protoimpl.X.CompressGZIP(file_simpli_echo_me_simpliEchoMe_proto_rawDescData)
	})
	return file_simpli_echo_me_simpliEchoMe_proto_rawDescData
}

var file_simpli_echo_me_simpliEchoMe_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_simpli_echo_me_simpliEchoMe_proto_goTypes = []interface{}{
	(*SayHiResponse)(nil),         // 0: simpli.simpli_echo_me.SayHiResponse
	(*EchoRequest)(nil),           // 1: simpli.simpli_echo_me.EchoRequest
	(*EchoResponse)(nil),          // 2: simpli.simpli_echo_me.EchoResponse
	(*EchoRememberRequest)(nil),   // 3: simpli.simpli_echo_me.EchoRememberRequest
	(*EchoRememberResponse)(nil),  // 4: simpli.simpli_echo_me.EchoRememberResponse
	(*SayHiRememberRequest)(nil),  // 5: simpli.simpli_echo_me.SayHiRememberRequest
	(*SayHiRememberResponse)(nil), // 6: simpli.simpli_echo_me.SayHiRememberResponse
	(*emptypb.Empty)(nil),         // 7: google.protobuf.Empty
}
var file_simpli_echo_me_simpliEchoMe_proto_depIdxs = []int32{
	7, // 0: simpli.simpli_echo_me.SimpliEchoMeService.SayHi:input_type -> google.protobuf.Empty
	1, // 1: simpli.simpli_echo_me.SimpliEchoMeService.Echo:input_type -> simpli.simpli_echo_me.EchoRequest
	3, // 2: simpli.simpli_echo_me.SimpliEchoMeService.EchoRemember:input_type -> simpli.simpli_echo_me.EchoRememberRequest
	5, // 3: simpli.simpli_echo_me.SimpliEchoMeService.SayHiRemember:input_type -> simpli.simpli_echo_me.SayHiRememberRequest
	0, // 4: simpli.simpli_echo_me.SimpliEchoMeService.SayHi:output_type -> simpli.simpli_echo_me.SayHiResponse
	2, // 5: simpli.simpli_echo_me.SimpliEchoMeService.Echo:output_type -> simpli.simpli_echo_me.EchoResponse
	4, // 6: simpli.simpli_echo_me.SimpliEchoMeService.EchoRemember:output_type -> simpli.simpli_echo_me.EchoRememberResponse
	6, // 7: simpli.simpli_echo_me.SimpliEchoMeService.SayHiRemember:output_type -> simpli.simpli_echo_me.SayHiRememberResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_simpli_echo_me_simpliEchoMe_proto_init() }
func file_simpli_echo_me_simpliEchoMe_proto_init() {
	if File_simpli_echo_me_simpliEchoMe_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_simpli_echo_me_simpliEchoMe_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SayHiResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_simpli_echo_me_simpliEchoMe_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EchoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_simpli_echo_me_simpliEchoMe_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EchoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_simpli_echo_me_simpliEchoMe_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EchoRememberRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_simpli_echo_me_simpliEchoMe_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EchoRememberResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_simpli_echo_me_simpliEchoMe_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SayHiRememberRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_simpli_echo_me_simpliEchoMe_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SayHiRememberResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_simpli_echo_me_simpliEchoMe_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_simpli_echo_me_simpliEchoMe_proto_goTypes,
		DependencyIndexes: file_simpli_echo_me_simpliEchoMe_proto_depIdxs,
		MessageInfos:      file_simpli_echo_me_simpliEchoMe_proto_msgTypes,
	}.Build()
	File_simpli_echo_me_simpliEchoMe_proto = out.File
	file_simpli_echo_me_simpliEchoMe_proto_rawDesc = nil
	file_simpli_echo_me_simpliEchoMe_proto_goTypes = nil
	file_simpli_echo_me_simpliEchoMe_proto_depIdxs = nil
}
